export const GENRE_OPTIONS = [
  'Science Fiction',
  'Horror',
  'Mystery',
  'Comedy',
  'Fantasy',
  'Drama',
  'Romance',
  'Adventure',
  'Crime',
  'Thriller',
  'Medical Drama',
  'Supernatural',
  'Political Drama',
  'Detective',
  'Teen Drama',
  'Marvel Universe',
] as const;

export const MAX_SELECTED_GENRES = 3;

export type GenreOption = typeof GENRE_OPTIONS[number];

export type GenreTheme = {
  primary: string;
  secondary: string;
  accent: string;
  ink: string;
  glow: string;
  icon: string;
  particles: string[];
  wave: OscillatorType;
  notes: number[];
  titleEn: string;
  titleUa: string;
  descriptionEn: string;
  descriptionUa: string;
};

export const GENRE_THEMES: Record<GenreOption, GenreTheme> = {
  'Science Fiction': {
    primary: '#0f4c81',
    secondary: '#38bdf8',
    accent: '#8b5cf6',
    ink: '#eff8ff',
    glow: 'rgba(56, 189, 248, 0.34)',
    icon: '🚀',
    particles: ['✨', '🪐', '☄️'],
    wave: 'triangle',
    notes: [392, 523, 659],
    titleEn: 'Neon future pulse',
    titleUa: 'Неоновий пульс майбутнього',
    descriptionEn: 'Cold cosmic light, satellite shimmer and a sleek starship atmosphere.',
    descriptionUa: 'Холодне космічне сяйво, мерехтіння супутників і атмосфера стильного зорельота.',
  },
  Horror: {
    primary: '#1a0b12',
    secondary: '#6f1020',
    accent: '#d62839',
    ink: '#fff3f5',
    glow: 'rgba(214, 40, 57, 0.38)',
    icon: '🩸',
    particles: ['🕷️', '🦇', '☠️'],
    wave: 'sawtooth',
    notes: [196, 174, 146],
    titleEn: 'Crimson midnight',
    titleUa: 'Багряна опівніч',
    descriptionEn: 'Deep shadows, sharp red flashes and a creepy cinema-jump vibe.',
    descriptionUa: 'Глибокі тіні, різкі червоні спалахи й моторошний вайб кіношного джампскеру.',
  },
  Mystery: {
    primary: '#11263d',
    secondary: '#44617e',
    accent: '#87b7ff',
    ink: '#edf6ff',
    glow: 'rgba(135, 183, 255, 0.30)',
    icon: '🔎',
    particles: ['🧩', '🕯️', '🔍'],
    wave: 'triangle',
    notes: [261, 311, 349],
    titleEn: 'Fog and clues',
    titleUa: 'Туман і підказки',
    descriptionEn: 'Silvery haze, coded shadows and the feeling that every detail matters.',
    descriptionUa: 'Сріблястий туман, закодовані тіні та відчуття, що важлива кожна дрібниця.',
  },
  Comedy: {
    primary: '#ffb703',
    secondary: '#fb8500',
    accent: '#ffd166',
    ink: '#4d2600',
    glow: 'rgba(255, 183, 3, 0.32)',
    icon: '🎭',
    particles: ['😂', '🎉', '⭐'],
    wave: 'square',
    notes: [659, 784, 880],
    titleEn: 'Sunny punchline',
    titleUa: 'Сонячний панчлайн',
    descriptionEn: 'Warm spotlights, playful sparkle and bright late-night-show energy.',
    descriptionUa: 'Теплі софіти, грайливі іскри та яскрава енергія вечірнього шоу.',
  },
  Fantasy: {
    primary: '#3a1c71',
    secondary: '#6a4cff',
    accent: '#f6c453',
    ink: '#f9f5ff',
    glow: 'rgba(106, 76, 255, 0.34)',
    icon: '🪄',
    particles: ['✨', '🦄', '🌙'],
    wave: 'sine',
    notes: [440, 554, 659],
    titleEn: 'Arcane glow',
    titleUa: 'Магічне сяйво',
    descriptionEn: 'Royal blues, enchanted gold and a world that feels one spell away.',
    descriptionUa: 'Королівські сині, зачароване золото й світ, що ніби за крок від закляття.',
  },
  Drama: {
    primary: '#243b53',
    secondary: '#52796f',
    accent: '#d8a47f',
    ink: '#f7fbff',
    glow: 'rgba(216, 164, 127, 0.26)',
    icon: '🎬',
    particles: ['🎞️', '💭', '🌫️'],
    wave: 'sine',
    notes: [293, 329, 392],
    titleEn: 'Slow-burn frame',
    titleUa: 'Кадр повільної напруги',
    descriptionEn: 'Muted cinematic tones, emotional depth and a premium festival mood.',
    descriptionUa: 'Стримані кінематографічні тони, емоційна глибина та настрій фестивального кіно.',
  },
  Romance: {
    primary: '#8e244d',
    secondary: '#f28482',
    accent: '#ffd6e0',
    ink: '#fff7fa',
    glow: 'rgba(242, 132, 130, 0.34)',
    icon: '💘',
    particles: ['💖', '🌹', '✨'],
    wave: 'sine',
    notes: [349, 440, 523],
    titleEn: 'Velvet heartbeat',
    titleUa: 'Оксамитовий пульс',
    descriptionEn: 'Soft rose light, warm glow and a polished love-story shimmer.',
    descriptionUa: 'М’яке рожеве світло, тепле сяйво і блиск витонченої love-story.',
  },
  Adventure: {
    primary: '#14532d',
    secondary: '#2a9d8f',
    accent: '#f4a261',
    ink: '#f3fff8',
    glow: 'rgba(42, 157, 143, 0.28)',
    icon: '🧭',
    particles: ['🌄', '🗺️', '🔥'],
    wave: 'triangle',
    notes: [392, 494, 587],
    titleEn: 'Trail of wonder',
    titleUa: 'Стежка пригод',
    descriptionEn: 'Fresh horizons, campfire warmth and the rush of setting off somewhere new.',
    descriptionUa: 'Свіжі горизонти, тепло багаття і драйв нової подорожі.',
  },
  Crime: {
    primary: '#1f2937',
    secondary: '#374151',
    accent: '#ef4444',
    ink: '#f9fafb',
    glow: 'rgba(239, 68, 68, 0.26)',
    icon: '🚨',
    particles: ['🚔', '📁', '⚖️'],
    wave: 'square',
    notes: [220, 277, 233],
    titleEn: 'After-hours district',
    titleUa: 'Нічний район',
    descriptionEn: 'Concrete shadows, police siren color and a city that never sleeps clean.',
    descriptionUa: 'Бетонні тіні, кольори сирен і місто, яке ніколи не буває по-справжньому чистим.',
  },
  Thriller: {
    primary: '#0f172a',
    secondary: '#1d3557',
    accent: '#ff6b35',
    ink: '#f8fbff',
    glow: 'rgba(255, 107, 53, 0.34)',
    icon: '⚡',
    particles: ['⚠️', '💥', '⏳'],
    wave: 'sawtooth',
    notes: [329, 415, 311],
    titleEn: 'Edge-of-seat voltage',
    titleUa: 'Напруга на межі',
    descriptionEn: 'Electric contrast, fast pressure and a frame that never lets you relax.',
    descriptionUa: 'Електричний контраст, швидка напруга і кадр, що не дає розслабитись.',
  },
  'Medical Drama': {
    primary: '#0f4c5c',
    secondary: '#5fa8d3',
    accent: '#e63946',
    ink: '#f4fdff',
    glow: 'rgba(95, 168, 211, 0.28)',
    icon: '🩺',
    particles: ['❤️', '🩹', '➕'],
    wave: 'sine',
    notes: [523, 659, 523],
    titleEn: 'Intensive blue light',
    titleUa: 'Світло операційної',
    descriptionEn: 'Clinical glow, urgent red beats and the drama of impossible choices.',
    descriptionUa: 'Клінічне сяйво, уривчасті червоні імпульси й драма неможливих рішень.',
  },
  Supernatural: {
    primary: '#1f2041',
    secondary: '#4b3f72',
    accent: '#00c2a8',
    ink: '#f5f4ff',
    glow: 'rgba(0, 194, 168, 0.30)',
    icon: '👻',
    particles: ['🕯️', '🌫️', '🔮'],
    wave: 'triangle',
    notes: [246, 329, 246],
    titleEn: 'Spectral whisper',
    titleUa: 'Примарний шепіт',
    descriptionEn: 'Moonlit haze, eerie teal shimmer and a story that slips beyond logic.',
    descriptionUa: 'Місячний серпанок, містичне бірюзове світіння та сюжет поза межами логіки.',
  },
  'Political Drama': {
    primary: '#1d3557',
    secondary: '#6c757d',
    accent: '#c1121f',
    ink: '#f8fbff',
    glow: 'rgba(193, 18, 31, 0.28)',
    icon: '🏛️',
    particles: ['🗳️', '📜', '🎙️'],
    wave: 'square',
    notes: [261, 220, 196],
    titleEn: 'Power corridor',
    titleUa: 'Коридори влади',
    descriptionEn: 'Steel tones, official red and a feeling that every sentence has a hidden price.',
    descriptionUa: 'Сталеві тони, офіційний червоний і відчуття, що кожна фраза має приховану ціну.',
  },
  Detective: {
    primary: '#132a3e',
    secondary: '#335c67',
    accent: '#ffd166',
    ink: '#f8fcff',
    glow: 'rgba(255, 209, 102, 0.32)',
    icon: '🕵️',
    particles: ['🔍', '🧠', '📌'],
    wave: 'triangle',
    notes: [329, 392, 349],
    titleEn: 'Case-board glow',
    titleUa: 'Сяйво дошки доказів',
    descriptionEn: 'Pinboard threads, brass highlights and the cool rhythm of deduction.',
    descriptionUa: 'Нитки доказів, латунні акценти та холодний ритм дедукції.',
  },
  'Teen Drama': {
    primary: '#355070',
    secondary: '#6d597a',
    accent: '#ff6f91',
    ink: '#fff8fd',
    glow: 'rgba(255, 111, 145, 0.30)',
    icon: '🎒',
    particles: ['📱', '💬', '🌟'],
    wave: 'sine',
    notes: [440, 494, 554],
    titleEn: 'Hallway neon',
    titleUa: 'Неон шкільного коридору',
    descriptionEn: 'Youthful glow, secret messages and polished coming-of-age intensity.',
    descriptionUa: 'Юнацьке сяйво, таємні повідомлення й драматична енергія дорослішання.',
  },
  'Marvel Universe': {
    primary: '#5b0f15',
    secondary: '#d62839',
    accent: '#4ea8ff',
    ink: '#fff6f7',
    glow: 'rgba(214, 40, 57, 0.36)',
    icon: '🛡️',
    particles: ['🦸', '⚡', '💥'],
    wave: 'sawtooth',
    notes: [262, 330, 392, 523],
    titleEn: 'Heroic red alert',
    titleUa: 'Супергеройська тривога',
    descriptionEn: 'Red-and-blue blockbuster energy, tech sparks and a full Marvel-event feeling.',
    descriptionUa: 'Червоно-синя блокбастерна енергія, технологічні спалахи й відчуття справжньої Marvel-події.',
  },
};
